### ISSUE TITLE
Mod operation fails in vba generated code result

### ISSUE THREAD

**Issue by douglashurt** [mepx/mep-basic-src#1]
Not sure this issue should be here, however, I did not know where to file an issue against the application version. 

Problem:
After doing the training on a data set and selecting to develop the code results in vba. I have noticed that the vba mod function fails most of the time with a division by zero error even though nether value is zero. From my understanding the vba system treats any value less then 1 as a zero, as vba doesn't handle floating points, in the mod operation. So, 12.3 mod 0.0156 will produce and error.

Solution:
Change the vba generated code
 from
 prg[#]=prg[#] mod prg[#] 
To
Prg[#]=Evaluate("MOD(" & prg[#] & "," & prg[#] & ")")

**Comment by douglashurt** [comment]
Found the correct project to open the issue for.

**Comment by mihaioltean** [comment]
You may report problem on our Google group: https://groups.google.com/g/mepx
However, I'll investigate the problem...
